---
services:
  app:
    build: .
    depends_on:
      ollama:
        condition: service_healthy
    volumes:
      - ./cache:/root/.cache:rw
      - .:/work:rw
    environment:
      FETCH: /reference_doc.txt
      OLLAMA_HOST: http://ollama:11434  # Use this in your app to connect to Ollama
    networks:
      - ollama-network
  ollama:
    image: ollama/ollama:latest
    # ports:
    #   - 11434:11434
    volumes:
      - $HOME/.ollama:/root/.ollama:rw
    healthcheck:
      test: bash -c "exec 6<> /dev/tcp/localhost/11434"
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ollama-network

networks:
  ollama-network:
    driver: bridge
